name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Remove old deployment
        uses: rossjrw/pr-preview-action@v1
        id: remove-deployment
        with:
          source-dir: src
          preview-branch: gh-pages
          umbrella-dir: preview
          action: remove
      
      - uses: nev7n/wait_for_response@v1
        env:
          URL: ${{ steps.remove-deployment.outputs.deployment-url }}
        with:
          url: ${{ steps.remove-deployment.outputs.deployment-url }}
          responseCode: 404
          timeout: 5000
          interval: 500

      
      # - name: Deploy
      #   uses: rossjrw/pr-preview-action@v1
      #   with:
      #     source-dir: src
      #     preview-branch: gh-pages
      #     umbrella-dir: preview
      #     action: deploy

  run-test:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: deploy-preview
    steps:
      - uses: actions/checkout@v3
      - name: Test
        env:          
          PR_NUMBER: ${{ github.event.number }}
        run: echo ${PR_NUMBER}