name: name: CI-Deploy

on:  
  pull_request:
    branches:
      - "main"

concurrency: pr-${{ github.ref }}

jobs:  
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./src
