name: Build and Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: write
concurrency: preview-${{ github.ref }}

jobs:
  build-and-deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          source-dir: src

