name: CI-PR

on:  
  pull_request:
    branches:
      - "main"

concurrency: pr-${{ github.ref }}

jobs:  
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./src
